### PR TITLE
Add hosts parameters

### PR DESCRIPTION
**Pull request by EulogyMondata**
That version add the hostnames parameters. We required it for an usecase.

### CODE REVIEW

**Review by TheGroundZero — APPROVED** [review]
Did a quick review of the changes but did not test with an actual report.

**Comment by TheGroundZero** [comment]
@EulogyMondata
Feel free to update the version number to `1.6`

**Comment by TheGroundZero** [comment]
@EulogyMondata 
Can you please update the Changelog? `docs/changelog.rst`
As well as the docs version number in `docs/conf.py`.

An update to `docs/usage/` would be welcome as well.

**Comment by TheGroundZero** [comment]
Please keep updates limited to added features and don't edit formatting too much.
E.g. there's no need to replace `-` by `+` for lists or replace string.format with f-strings.

**Review by LaCapitainerie — CHANGES_REQUESTED** [review]
Some of your changes, made the code less readable and fluid : 
image
By convention we align items in a way it look like a table.
Others changes would be the one liner you made from most of dictionnary, and on top of that, keep a single way to display them, one-liner or table, but you mixed theses two.

I would tell you to remove your typo changes and only keep the essential of the issue to avoid another commit to fixes all the typo

**Pull request closed without merging**
